name: Merge Queue

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  check-linux:
    name: Check [Linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dsherret/rust-toolchain-file@v1

      - name: Check
        run: cargo check
